// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRd3sIJLr__TS9hfBgqENl7n4ECrwvqyc',
    appId: '1:1028893795079:web:8877c6ff17d1eb4c2e5ba2',
    messagingSenderId: '1028893795079',
    projectId: 'laporbook-2aa20',
    authDomain: 'laporbook-2aa20.firebaseapp.com',
    databaseURL: 'https://laporbook-2aa20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporbook-2aa20.appspot.com',
    measurementId: 'G-61SBHES8BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4m30Uu0hNcO7YErBw3jLIepYOkCGlsEo',
    appId: '1:1028893795079:android:b80e5824fed0f6c22e5ba2',
    messagingSenderId: '1028893795079',
    projectId: 'laporbook-2aa20',
    databaseURL: 'https://laporbook-2aa20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporbook-2aa20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzBx2PQyW5cCm5G3_iV4SOTuiKDYI-OEs',
    appId: '1:1028893795079:ios:144cbbd0747e5d702e5ba2',
    messagingSenderId: '1028893795079',
    projectId: 'laporbook-2aa20',
    databaseURL: 'https://laporbook-2aa20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporbook-2aa20.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );
}
